---------------------------------------------
grid_of    = 32
size_of    = 8
address_of = 1600
name_of    = DEFINES_FIELD
value_of   = DEADBEEFh
is_valid   = 1
---------------------------------------------
grid_of    = 32
size_of    = 8
address_of = 1872
name_of    = DEFINES_ARRAY_2_FIELD_1_1_2
value_of   = Ah
is_valid   = 1
=============================================
grid_of    = 32
size_of    = 8
address_of = 1600
name_of    = DEFINES_FIELD
value_of   = DEADBEEFh
is_valid   = 1
=============================================
grid_of    = 32
size_of    = 32
address_of = 1632
name_of    = DEFINES_REGISTER
value_of   = (null)
is_valid   = 1
=============================================
grid_of    = 32
size_of    = 4
address_of = 1632
name_of    = DEFINES_REGISTER_FIELD
value_of   = Ch
is_valid   = 1
=============================================
grid_of    = 32
size_of    = 8
address_of = 1872
name_of    = DEFINES_ARRAY_2_FIELD_1_1_2
value_of   = Ah
is_valid   = 1
=============================================
grid_of    = 32
size_of    = 8
address_of = 1776
name_of    = DEFINES_ARRAY_2_FIELD_1_1_5
value_of   = Ah
is_valid   = 0
