
sub compile {
	my $mode = shift;
	rm("test.exe $mode.act");
	execute("gcc -I . -o test.exe test.c");
	execute("./test.exe > $mode.act") if -e "test.exe";
	diff("$mode.act","$mode.exp");
	rm("test.h test.exe $mode.act");
}

sub head {
	my $act = shift;
	my $exp = shift;
	my $n   = shift; $n = 1 unless defined $n;
	execute("head -$n $exp > $exp.head");
	diff($act,"$exp.head");
	rm("$act $exp.head");
}

sub tail {
	my $act = shift;
	my $exp = shift;
	my $n   = shift; $n = 1 unless defined $n;
	execute("tail -$n $exp > $exp.tail");
	diff($act,"$exp.tail");
	rm("$act $exp.tail");
}

describe("defines.pl", sub {

	describe("C dialect", sub {

		describe("list format",sub {

			describe("debug mode", sub {

				it("is generated by default", sub {
					rm("*.act");
					spacecraft("test.rf defines.pl c_list_debug.act");
					diff("c_list_debug.act","c_list_debug.exp");
					rm("*.act");
				});

				it("compiles & executes", sub {
					rm("*.act");
					spacecraft("test.rf defines.pl test.h");
					compile("c_exec_debug");
				});

			});

			describe("optimized mode", sub {

				it("is generated with the -?-o(ptimize)? switch", sub {
					foreach my $optimize ("-o","--o","-optimize","--optimize") {
						rm("*.act");
						spacecraft("test.rf defines.pl $optimize c_list_opt.act");
						diff("c_list_opt.act","c_list_opt.exp");
						rm("*.act");
					}
				});

				it("compiles & executes", sub {
					rm("*.act");
					spacecraft("test.rf defines.pl -o test.h");
					compile("c_exec_opt");
				});

			});

		});

		describe("struct format",sub {

			describe("debug mode", sub {

				it("is generated with the --structs switch", sub {
					foreach my $structs ("--structs") {
						rm("*.act");
						spacecraft("test.rf defines.pl $structs c_struct_debug.act");
						diff("c_struct_debug.act","c_struct_debug.exp");
						rm("*.act");
					}
				});

				it("compiles & executes", sub {
					rm("*.act");
					spacecraft("test.rf defines.pl --structs test.h");
					compile("c_exec_debug");
				});

			});

			describe("optimized mode", sub {

				it("is generated with the --structs and -?-o(ptimize)? switches", sub {
					foreach my $structs ("--structs") {
						foreach my $optimize ("-o","--o","-optimize","--optimize") {
							rm("*.act");
							spacecraft("test.rf defines.pl $optimize $structs c_struct_opt.act");
							diff("c_struct_opt.act","c_struct_opt.exp");
							rm("*.act");
						}
					}
				});

				it("compiles & executes", sub {
					spacecraft("test.rf defines.pl -o --structs test.h");
					compile("c_exec_opt");
				});

			});

		});

		describe("storage abstraction macros", sub {

			it("are omitted with the -?-c(onstants) switch", sub {
				rm("*.act");
				foreach my $constants ("-c","--c","-constants","--constants") {
					spacecraft("test.rf defines.pl $constants c_list_debug.act");
					tail("c_list_debug.act","c_list_debug.exp",9);

					spacecraft("test.rf defines.pl $constants -o c_list_opt.act");
					tail("c_list_opt.act","c_list_opt.exp",9);

					spacecraft("test.rf defines.pl $constants --structs c_struct_debug.act");
					tail("c_struct_debug.act","c_struct_debug.exp",9);

					spacecraft("test.rf defines.pl $constants --structs -o c_struct_opt.act");
					tail("c_struct_opt.act","c_struct_opt.exp",9);
				}
			});

		});

		describe("node constants", sub {

			it("are omitted with the -?-s(torage) switch", sub {
				rm("*.act");
				foreach my $storage ("-s","--s","-storage","--storage") {
					spacecraft("test.rf defines.pl $storage c_list_debug.act");
					head("c_list_debug.act","c_list_debug.exp",77);

					spacecraft("test.rf defines.pl $storage -o c_list_opt.act");
					head("c_list_opt.act","c_list_opt.exp",77);

					spacecraft("test.rf defines.pl $storage --structs c_struct_debug.act");
					head("c_struct_debug.act","c_struct_debug.exp",72);

					spacecraft("test.rf defines.pl $storage --structs -o c_struct_opt.act");
					head("c_struct_opt.act","c_struct_opt.exp",69);
				}
			});

		});

		describe("grid size", sub {

		});

	});

	describe("Verilog dialect", sub {

	});

});
